# A minimal left prompt
format = '''$character'''

# move the rest of the prompt to the right
right_format = """$all"""
# add_newline = false

[character]
success_symbol = '''[\(λ\)](#e600f8)'''

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = true 

[rust]
disabled = true

[status]
format = '[$symbol $status]($style) '
disabled = false

[package]
disabled = true
