# A minimal left prompt
format = '''$character'''

# move the rest of the prompt to the right
right_format = """$all"""
add_newline = false

[character]
success_symbol = '''\([λ](bright-red)\) '''

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
truncation_length = 2
truncation_symbol = "..."
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△](bold bright-blue)'
